name: Run tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      group:
        description: "Какую группу тестов прогнать"
        type: choice
        default: full
        options:
          - smoke
          - full

jobs:
  smoke:
    if: github.event_name == 'push' || github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.group == 'smoke')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run smoke tests
        env:
          GITHUB_TOKEN: ${{secrets.API_TOKEN}}
        run: pytest -m smoke --alluredir=./allure-results

      - name: Upload allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-smoke
          path: allure-results

  full:
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.group == 'full')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run all tests
        env:
          GITHUB_TOKEN: ${{secrets.API_TOKEN}}
        run: pytest --alluredir=./allure-results

      - name: Upload allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-full
          path: allure-results